pks/admin2/urls.py
#-*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import url

from admin2 import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^placed/$', views.placed, name='placed'),
    url(r'^placed/(?P<uplace_id>[0-9A-Za-z]+)\.uplace/$', views.placed_detail, name='placed_detail'),
    url(r'^places/$', views.places, name='places'),
    url(r'^url_placed/$', views.url_placed, name='url_placed'),
]

pks/pks/urls.py
#-*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import url, include
from django.contrib import admin

from rest_framework.routers import DefaultRouter
from filebrowser.sites import site as fb_site
from django.conf import settings
from django.conf.urls.static import static
from account import views as account_views
from image import views as image_views
from url import views as url_views
from place import views as place_views
from content import views as content_views
from importer import views as importer_views
from tag import views as tag_views
from etc import views as etc_views


router = DefaultRouter()
router.register(r'vds', account_views.VDViewset)
router.register(r'users', account_views.UserViewset)
router.register(r'rus', account_views.RealUserViewset)
router.register(r'storages', account_views.StorageViewset)
router.register(r'trackings', account_views.TrackingViewset)

router.register(r'rfs', image_views.RawFileViewset)
router.register(r'imgs', image_views.ImageViewset)
router.register(r'urls', url_views.UrlViewset)
router.register(r'lps', content_views.LegacyPlaceViewset)
router.register(r'phones', content_views.PhoneNumberViewset)
router.register(r'pnames', content_views.PlaceNameViewset)
router.register(r'addrs', content_views.AddressViewset)
router.register(r'pnotes', content_views.PlaceNoteViewset)
router.register(r'inotes', content_views.ImageNoteViewset)

router.register(r'places', place_views.PlaceViewset)
router.register(r'pps', place_views.PostPieceViewset)
router.register(r'uplaces', place_views.UserPlaceViewset)
router.register(r'proxies', importer_views.ProxyViewset)
router.register(r'importers', importer_views.ImporterViewset)
router.register(r'iplaces', importer_views.ImportedPlaceViewset)

router.register(r'tags', tag_views.TagViewset)
router.register(r'uptags', tag_views.UserPlaceTagViewset)
router.register(r'ptags', tag_views.PlaceTagViewset)

router.register(r'notices', etc_views.NoticeViewset)
router.register(r'inquiries', etc_views.InquiryViewset)


def redirect_to_google_shortener(request, key):
    from django.shortcuts import redirect
    return redirect('http://goo.gl/%s' % key)


urlpatterns = [
    url(r'^$', include('home.urls')),
    url(r'^', include(router.urls)),
    url(r'^g/(?P<key>.+)', redirect_to_google_shortener, name='diaries'),

    url(r'^admin2/', include('admin2.urls', namespace='admin2')),
    url(r'^ui/', include('ui.urls', namespace='ui')),

    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^admin/filebrowser/', include(fb_site.urls)),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pks/ui/urls.py
#-*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import url

from ui import views


urlpatterns = [
    # 장소 태깅 서비스
    url(r'^diaries/$', views.diaries, name='diaries'),
    url(r'^diaries/init', views.init, name='init'),
    url(r'^diaries/register_email', views.register_email, name='register_email'),
    url(r'^diaries/(?P<uplace_id>[0-9A-Za-z]+)\.uplace/paste/$', views.paste, name='paste'),
    url(r'^diaries/(?P<uplace_id>[0-9A-Za-z]+)\.uplace/temp/$', views.temp, name='temp'),
    url(r'^diaries/(?P<uplace_id>[0-9A-Za-z]+)\.uplace/make_shorten_url/$', views.make_shorten_url, name='make_shorten_url'),
    url(r'^diaries/(?P<enc_uplace_id>[0-9A-Za-z-_]+)/$', views.detail, name='detail'),

    # 이메일 인증
    url(r'^confirm_ok/$', views.confirm_ok, name='confirm_ok'),
    url(r'^confirm_fail/$', views.confirm_fail, name='confirm_fail'),
]

pks/admin2/models.py
#-*- coding: utf-8 -*-
from __future__ import unicode_literals

pks/place/models.py
#-*- coding: utf-8 -*-
from __future__ import unicode_literals

from uuid import UUID
from django.contrib.gis.db import models
from base64 import b16encode
from django.contrib.postgres.fields import JSONField
from django.contrib.gis.measure import D
from django.contrib.gis.db.models.functions import Distance
from cryptography.fernet import Fernet
from requests import post as requests_post
from json import loads as json_loads
from rest_framework import status

from account.models import VD
from base.utils import get_timestamp, BIT_ON_8_BYTE, get_uuid_from_ts_vd
from place.post import PostBase
from base.models import Point
from content.models import PlaceName
from base.libs import distance_geography
from pks.settings import VD_ENC_KEY
from base.cache import cache_get_or_create, cache_expire

RADIUS_LOCAL_RANGE = 150


class Place(models.Model):

    lonLat = models.PointField(blank=True, null=True, default=None, geography=True)
    placeName = models.ForeignKey(PlaceName, on_delete=models.SET_DEFAULT, null=True, default=None, related_name='places')

    def __init__(self, *args, **kwargs):
        self._cache_placePost = None
        super(Place, self).__init__(*args, **kwargs)

    def __unicode__(self):
        if self.placeName:
            return self.placeName.content
        return 'No named place object'

    def _clearCache(self):
        cache_expire(None, 'placePost_%s' % self.id)
        self._cache_placePost = None

    @property
    def placePost(self):
        def helper(self):
            pb = PostBase()
            for pp in self.pps.all().filter(uplace=None).order_by('id'):
                if pp.is_bounded:
                    continue
                pb_new = pp.pb
                pb.update(pb_new, pp.is_add)
            pb.place_id = self.id
            pb.normalize()
            return pb
        if not self._cache_placePost:
            self._cache_placePost, is_created = cache_get_or_create(None, 'placePost_%s' % self.id, None, helper, self)
        return self._cache_placePost

    @property
    def _totalPost(self):
        pb = PostBase()
        for pp in self.pps.all().order_by('id'):
            pb.update(pp.pb, pp.is_add)
        pb.place_id = self.id
        pb.normalize()
        return pb


    # TODO : 값들이 서로 모순되는 경우에 대한 처리
    # TODO : 추가로 실시간으로 같은 place 를 찾을 수 있는 상황이라면 곧바로 처리
    # TODO : 장소이름만 단독으로 먼저 붙이고, 그 이후에 좌표를 추가하는 경우 현재 장소화가 안됨.
    @classmethod
    def get_or_create_smart(cls, pb, vd):

        #######################################
        # Direct Placed Part
        #######################################

        # place_id 가 명확히 지정된 경우
        if pb.place_id:
            return cls.objects.get(id=pb.place_id), False

        # uplace, lonLat 조회
        uplace = None
        if pb.uplace_uuid:
            uplace = UserPlace.get_from_uuid(pb.uplace_uuid)
        lonLat = pb.lonLat or (uplace and uplace.lonLat)

        # Placed by LegacyPlace
        lp = None
        if pb.lps:
            pb.normalize()
            lp = pb.lps[0]
            if lp.place:
                place = lp.place
                if not place.placeName or not place.lonLat:
                    if pb.name and pb.lonLat:
                        place.placeName = pb.name
                        place.lonLat = pb.lonLat
                        place.save()
                        PostPiece.create_smart_4place(place, vd, pb)
                return place, False

        # Placed by placeName/lonLat
        placeName = pb.name
        if placeName and lonLat:
            qs = Place.objects.filter(placeName=placeName)\
                .filter(lonLat__distance_lte=(lonLat, D(m=RADIUS_LOCAL_RANGE)))\
                .annotate(distance=Distance('lonLat', lonLat)).order_by('distance')
            if qs and qs[0]:
                _place = qs[0]
                # TODO : 리팩토링 필요
                if lp:
                    lp.place = _place
                    lp.save()
                    PostPiece.create_smart_4place(_place, vd, pb)
                return _place, False


        #######################################
        # Indirect Placed Part
        #######################################

        # Placed by LegacyPlace
        if lp:
            _place = Place.objects.create(lonLat=lonLat, placeName=placeName)
            lp.place = _place
            lp.save()
            PostPiece.create_smart_4place(_place, vd, pb)
            return _place, True

        # Placed by placeName/lonLat
        if placeName and lonLat:
            if not pb.lonLat:
                pb.point = Point(lonLat)
            _place = Place.objects.create(lonLat=lonLat, placeName=placeName)
            PostPiece.create_smart_4place(_place, vd, pb)
            return _place, True

        # last : old_place
        if uplace:
            return uplace.place, False

        return None, False


    @property
    def lonLat_json(self):
        return Point(self.lonLat).json


class UserPlace(models.Model):
    id = models.UUIDField(primary_key=True, default=None)
    vd = models.ForeignKey(VD, on_delete=models.SET_DEFAULT, null=True, default=None, related_name='uplaces')
    place = models.ForeignKey(Place, on_delete=models.SET_DEFAULT, null=True, default=None, related_name='uplaces')
    modified = models.BigIntegerField(blank=True, null=True, default=None)
    lonLat = models.PointField(blank=True, null=True, default=None, geography=True)
    mask = models.SmallIntegerField(blank=True, null=True, default=None)

    parent = models.ForeignKey('self', on_delete=models.SET_DEFAULT, null=True, default=None, related_name='childs')
    shorten_url = models.CharField(max_length=254, blank=True, null=True, default=None)

    def __init__(self, *args, **kwargs):
        self._cache_userPost = None
        self._cache_total_pps = None
        self._cache_prev_tags = None
        self._cache_prev_NLL = None
        self._cache_vd_ids = None
        self._origin = None
        self._search_tags = None
        super(UserPlace, self).__init__(*args, **kwargs)

    def __unicode__(self):
        if self.place and self.place.placeName:
            return self.place.placeName.content
        return 'No named uplace object'

    @property
    def uuid(self):
        return '%s.%s' % (b16encode(self.id.bytes), 'uplace',)

    @classmethod
    def get_from_uuid(cls, _uuid):
        splits = _uuid.split('.')
        if splits[1] not in ('uplace', 'iplace'):
            raise ValueError
        _id = UUID(splits[0])
        return cls.objects.get(id=_id)

    def placed(self, place, lonLat=None):
        self.place = place
        self.lonLat = lonLat or place.lonLat or self.lonLat
        self.save()
        for pp in self.pps.all():
            pp.place = place
            pp.save()

    @classmethod
    def get_or_create_smart(cls, pb, vd):
        place, is_created = Place.get_or_create_smart(pb, vd)
        uplace = None
        is_uplace_created = False

        # TODO : uplace 좀 더 찾기...
        if pb.uplace_uuid:
            uplace = cls.get_from_uuid(pb.uplace_uuid)
        #if not uplace and place:
        #    uplace = UserPlace.objects.filter(vd_id__in=vd.realOwner_vd_ids, place=place).order_by('id').first()

        lonLat = (place and place.lonLat) or pb.lonLat or (uplace and uplace.lonLat)

        # 실시간 장소화
        if not uplace:
            uplace = cls.objects.create(vd=vd, place=place, lonLat=lonLat)
            is_uplace_created = True
        elif not uplace.place:
            if place:
                uplace.placed(place, lonLat)
        else:
            if place and uplace.place != place:
                uplace.placed(place, lonLat)
                # TODO : 로그 남겨서 Place Merge 시 우선순위 높여 참고하기

        # 결과 처리
        pb.place_id = uplace.place_id
        pb.uplace_uuid = uplace.uuid
        return uplace, is_uplace_created

    # TODO : DB 저장 회수 많음. 튜닝 필요
    def get_or_create_child(self, place=None):
        if self.parent:
            print('[Child cannot created from other Child]')
            print('[Child info]')
            self.dump()
            print('[Parent info]')
            self.parent.dump()
            print('------------------------------')
            raise NotImplementedError
        self.is_parent = True
        self.place = None
        self.save()

        pb = PostBase()
        pb.place_id = place and place.id or None
        child, is_created = UserPlace.get_or_create_smart(pb, self.vd)
        # 하기 is_created 에 의한 if 처리는 반드시 해야 함
        # 이를 하지 않으면 생성(U1) --> URL장소화(P1) --> 생성(U2) --> URL장소(P2) 에서 문제 발생
        # 위 문제가 아니더라도 성능상 유리
        if is_created:
            child.parent = self
            child.save()
        return child, is_created

    def process_child(self, place=None):
        if self.is_parent:
            self.get_or_create_child(place)
        else:
            if self.place:
                self.get_or_create_child(self.place)    # 기존 매핑 Place 로도 별도 child 생성
                self.get_or_create_child(place)
            else:
                self.placed(place)

    @property
    def post_cache_name(self):
        return 'userPost_%s' % self.uuid

    def _clearCache(self):
        cache_expire(self.vd, self.post_cache_name)
        self._cache_userPost = None
        self._cache_total_pps = None
        self._cache_prev_tags = None
        self._cache_prev_NLL = None
        self._cache_vd_ids = None
        if self.place:
            self.place._clearCache()

    @property
    def vd_ids(self):
        if self._cache_vd_ids is None:
            self._cache_vd_ids = []
            if self.vd:
                self._cache_vd_ids.extend(self.vd.realOwner_vd_ids)
                self._cache_vd_ids.extend(self.vd.realOwner_publisher_ids)
        return self._cache_vd_ids

    @property
    def base_post(self):
        base_post = self.parent and self.parent.userPost or PostBase()
        # TODO : 아래 코드가 기억나지 않음 ㅠ_ㅜ 정체 파악 후 다시 부활
        #base_post.reset_except_region_property()

pks/url/models.py
#-*- coding: utf-8 -*-
from __future__ import unicode_literals

from re import compile as re_compile
from rest_framework import status
from django.contrib.gis.db import models

from base.models import Content
from base.legacy.urlnorm import norms as url_norms
from requests import get as requests_get
from place.models import Place, PostPiece

URL_REGEX_NAVER_SHORTENER_URLS = [
    re_compile(r'^https?://me2\.do/[A-za-z0-9_\-]+$'),
    re_compile(r'^https?://naver\.me/[A-za-z0-9_\-]+$'),
]
URL_REGEX_4SQUARE_SHORTENER_URL = re_compile(r'^https?://4sq\.com/[A-za-z0-9_\-]+$')


class Url(Content):

    places = models.ManyToManyField(Place, through='UrlPlaceRelation', related_name='urls')

    # MUST override
    @property
    def contentType(self):
        return 'url'

    @property
    def accessedType(self):
        return 'html'

    # CAN override
    @classmethod
    def normalize_content(cls, raw_content):
        url = url_norms(raw_content)

        # javascript 로 동작해서 body 를 받아야만 하는 단축 URL 처리 : 현재는 네이버 단축 URL 만 확인됨
        if URL_REGEX_NAVER_SHORTENER_URLS[0].match(url) or URL_REGEX_NAVER_SHORTENER_URLS[1].match(url):
            headers = {'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36'}
            r = requests_get(url, headers=headers)
            content_type = r.headers.get('content-type')
            if r.status_code in (status.HTTP_200_OK,) and content_type and content_type.startswith('text/html'):
                str = r.content
                if str.startswith(b'<script>window.location.replace("'):
                    pos1 = str.index('"') + 1
                    pos2 = str.index('"', pos1)
                    if pos1 < pos2:
                        url_redirected = str[pos1:pos2]
                        url = url_norms(url_redirected)

        # URL redirect 처리 : 301 에 의한 URL redirect : 현재는 포스퀘어 단축 URL 만 처리
        elif URL_REGEX_4SQUARE_SHORTENER_URL.match(url):
            headers = {'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36'}
            r = requests_get(url, headers=headers)
            content_type = r.headers.get('content-type')
            if r.status_code in (status.HTTP_200_OK,) and content_type and content_type.startswith('text/html'):
                url_redirected = r.url
                url = url_norms(url_redirected)

        return url

    def add_place(self, place):
        upr, is_created = UrlPlaceRelation.objects.get_or_create(url=self, place=place)
        if is_created:
            pps = PostPiece.objects.filter(data__urls__contains=[self.ujson])
            for pp in pps:
                uplace = pp.uplace
                uplace.process_child(place)
        return upr

    # TODO : add_place() 에 의해 생성된 UserPlace 에 대해, remove_place() 가 호출되면 어떻게 처리하는 것이 좋을지 고민 후 구현
    def remove_place(self, place):
        upr = UrlPlaceRelation.objects.get(url=self, place=place)
        upr.delete()


class UrlPlaceRelation(models.Model):
    url = models.ForeignKey(Url, on_delete=models.SET_DEFAULT, null=True, default=None, related_name='+')
    place = models.ForeignKey(Place, on_delete=models.SET_DEFAULT, null=True, default=None, related_name='+')

    class Meta:
        unique_together = ('url', 'place',)

pks/admin2/templates/admin2/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>PlaceKoob Custom Admin</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
</head>
<body>
<div class="container">
    <div class="row">
        <h1>{% block header_text %}{% endblock %}</h1>
        <br/>
        <form method="POST" action="{% block form_action %}{% endblock %}">
            {% csrf_token %}
            {% block table %}
            {% endblock %}
        </form>
    </div>
</div>
</body>
</html>

pks/admin2/templates/admin2/index.html
{% extends 'admin2/base.html' %}

{% block header_text %}PlaceKoob Custom Admin - Home{% endblock %}

{% block table %}
    <ul>
        <li>
            <a href="/admin2/placed/">장소화 하기</a>
        </li>
        <li>
            <a href="/admin2/places/">장소화 완료 목록</a>
        </li>
        <li>
            <a href="/admin2/url_placed/">URL 장소화 하기</a>
        </li>
    </ul>
{% endblock %}

pks/admin2/templates/admin2/mapping_detail.html
{% extends 'admin2/base.html' %}

{% block header_text %}PlaceKoob Custom Admin - Mapping Detail{% endblock %}

{% block table %}
    <table class="table">
        <tr>
            <td>
                <a href="http://map.naver.com/?dlevel=13&x={{ userPost.lonLat.x }}&y={{ userPost.lonLat.y }}" target="_blank">
                    위도: {{ userPost.lonLat.y }}<br/>
                    경도: {{ userPost.lonLat.x }}
                </a>
            </td>
            <td>
                도로명주소: {{ userPost.addr1 }}<br/>
                지번 주소 : {{ userPost.addr2 }}<br/>
                범위 주소 : {{ userPost.addr3 }}<br/>
            </td>
            <td>
                {% for image in userPost.images %}
                    <a href="{{ image.content }}" target="_blank">
                        <img src="{{ image.url_summarized }}"/>
                    </a>
                {% endfor %}
            </td>
            <td>
                {% for url in userPost.urls %}
                    <a href="{{ url.content }}" target="_blank">{{ url.content }}</a>
                {% endfor %}
            </td>
            <td>
                {% for note in userPost.notes %}
                    <a href='http://www.google.co.kr/?gws_rd=ssl#q="{{ note.content }}"' target="_blank">{{ note.content }}</a>
                {% endfor %}
            </td>
        </tr>
        <tr>
            <td>
                <a href="http://map.naver.com/?dlevel=13&x={{ placePost.lonLat.x }}&y={{ placePost.lonLat.y }}" target="_blank">
                    위도: {{ placePost.lonLat.y }}<br/>
                    경도: {{ placePost.lonLat.x }}
                </a>
            </td>
            <td>
                도로명주소: {{ placePost.addr1 }}<br/>
                지번 주소 : {{ placePost.addr2 }}<br/>
                범위 주소 : {{ placePost.addr3 }}<br/>
            </td>
            <td>
                이름 : {{ placePost.name }}
            </td>
            <td>
                {% for url in placePost.urls %}
                    <a href="{{ url.content }}" target="_blank">{{ url.content }}</a>
                {% endfor %}
            </td>
            <td>
                전화번호 : {{ placePost.phone }}
            </td>
        </tr>
    </table>
    <table class="table">
        <tr>
        <tr>
            <td colspan="2">
                <div class="jumbotron">
                    LegacyPlace URL : <input type="text" id="id_url" name="url" class="form-control input-lg"/>
                </div>
            </td>
        </tr>
        <tr>
            <td>
                <div class="jumbotron">
                    PlaceName : <input type="text" id="id_placeName" name="placeName" class="form-control input-lg"/>
                </div>
            </td>
            <td>
                <div class="jumbotron">
                    LonLat : <input type="text" id="id_lonLat" name="lonLat" class="form-control input-lg"/>
                </div>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <div class="jumbotron">
                    <input type="submit" class="form-control input-lg"/>
                </div>
            </td>
        </tr>
    </table>
{% endblock %}

pks/admin2/templates/admin2/placed_detail.html
{% extends 'admin2/base.html' %}

{% block header_text %}PlaceKoob Custom Admin - Placed Detail{% endblock %}

{% block table %}
    {% if not placePost %}
    <table class="table">
        <tr>
            <td colspan="2">
                <div class="jumbotron">
                    LegacyPlace URL : <input type="text" id="id_url" name="url" class="form-control input-lg"/>
                </div>
            </td>
        </tr>
        <tr>
            <td>
                <div class="jumbotron">
                    PlaceName : <input type="text" id="id_placeName" name="placeName" class="form-control input-lg"/>
                </div>
            </td>
            <td>
                <div class="jumbotron">
                    LonLat : <input type="text" id="id_lonLat" name="lonLat" class="form-control input-lg" value="{{ default_lonLat }}"/>
                </div>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <div class="jumbotron">
                    <input type="submit" class="form-control input-lg"/>
                </div>
            </td>
        </tr>
    </table>
    {% endif %}

    <table class="table">
        <tr>
            <td>
                <a href="{{ placePost.map_url_naver }}" target="_blank">
                    위도: {{ placePost.lonLat.y }}<br/>
                </a>
                <a href="{{ placePost.map_url_google }}" target="_blank">
                    경도: {{ placePost.lonLat.x }}<br/>
                </a>
            </td>
            <td>
                도로명주소: {{ placePost.addr1 }}<br/>
                지번 주소 : {{ placePost.addr2 }}<br/>
                범위 주소 : {{ placePost.addr3 }}<br/>
            </td>
            <td>
                이름 : {{ placePost.name }}
            </td>
            <td>
                {% for url in placePost.urls %}
                    <a href="{{ url.content }}" target="_blank">{{ url.cont
ent }}</a><br/>
                {% endfor %}
            </td>
            <td>
                전화번호 : {{ placePost.phone }}
            </td>
        </tr>
    </table>
    <table class="table">
        <tr>
            <td>
                <a href="{{ userPost.map_url_daum }}" target="_blank">
                    위도: {{ userPost.lonLat.y }}<br/>
                </a>
                <a href="{{ userPost.map_url_google }}" target="_blank">
                    경도: {{ userPost.lonLat.x }}<br/>
                </a>
                <br/>
                도로명주소: {{ userPost.addr1 }}<br/>
                지번 주소 : {{ userPost.addr2 }}<br/>
                범위 주소 : {{ userPost.addr3 }}<br/>
                <br/>
                {% for url in userPost.urls %}
                    <a href="{{ url.content }}" target="_blank">{{ url.content }}</a><br/>
                {% endfor %}
                <br/>
                {% for note in userPost.notes %}
                    <a href='http://www.google.co.kr/?gws_rd=ssl#q="{{ note.content_for_search }}"' target="_blank">{{ note.content }}</a><br/>
                {% endfor %}
                <br/>
                {% for tag in userPost.tags %}
                    {{ tag.content }},
                {% endfor %}
            </td>
            <td>
                <table>
                    {% for image in userPost.images %}
                        <tr>
                            <td>
                                <a href="{{ image.url_for_access }}" target="_blank"><img src="{{ image.url_summarized }}"/></a>
                            </td>
                            <td>
                                &nbsp;
                            </td>
                            <td>
                                timestamp : {{ image.timestamp }}<br/>
                                {% for tagName in image.ctags.tagNames %}
                                    {{ tagName.T }} : {{ tagName.A }}<br/>
                                {% endfor %}
                            </td>
                        </tr>
                    {% endfor %}
                </table>
            </td>
        </tr>
    </table>

    {% if placePost %}
    <table class="table">
        <tr>
            <td colspan="2">
                <div class="jumbotron">
                    LegacyPlace URL : <input type="text" id="id_url" name="url" class="form-control input-lg"/>
                </div>
            </td>
        </tr>
        <tr>
            <td>
                <div class="jumbotron">
                    PlaceName : <input type="text" id="id_placeName" name="placeName" class="form-control input-lg"/>
                </div>
            </td>
            <td>
                <div class="jumbotron">
                    LonLat : <input type="text" id="id_lonLat" name="lonLat" class="form-control input-lg" value="{{ default_lonLat }}"/>
                </div>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <div class="jumbotron">
                    <input type="submit" class="form-control input-lg"/>
                </div>
            </td>
        </tr>
    </table>
    {% endif %}
{% endblock %}

pks/admin2/templates/admin2/url_placed.html
{% extends 'admin2/base.html' %}

{% block header_text %}PlaceKoob Custom Admin - Placed Detail{% endblock %}

{% block table %}
    {% if url %}
    <table class="table">
        <tr>
            <td>
                URL : {{  url  }}
            </td>
        </tr>
        <tr>
            <td>
                {% for place in places %}
                    {{ place }}<br/>
                {% endfor %}
            </td>
        </tr>
    </table>
    <br/>
    {% endif %}

    <table class="table">
        <tr>
            <td>
                <div class="jumbotron">
                    URL : <input type="text" id="id_url" name="url" class="form-control input-lg" value="{{  url  }}"/>
                </div>
            </td>
        </tr>
        <tr>
            <td>
                <div class="jumbotron">
                    Places : <textarea id="id_places" name="places" class="form-control textarea"></textarea>
                </div>
            </td>
        </tr>
        <tr>
            <td>
                <div class="jumbotron">
                    <input type="submit" class="form-control input-lg"/>
                </div>
            </td>
        </tr>
    </table>
{% endblock %}